name: usher
channels:
  - defaults                                                                                                                                                                                                    
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - cxx-compiler
  - protobuf
  - cmake
  - make
  - boost-cpp
  - mafft
  - python
  - git
  - wget
  - rsync
  - intel::impi-devel=2021.4.0