name: usher
channels:
  - defaults                                                                                                                                                                                                    
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - cxx-compiler
  - protobuf>=3.18
  - cmake>=3.19
  - make
  - boost-cpp
  - mafft
  - python
  - git
  - wget
  - rsync
  - openmpi
  - isa-l
